//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slate_EK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FASTener")]
        public string AppTitle {
            get {
                return ((string)(this["AppTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FASTener")]
        public string ShortTitle {
            get {
                return ((string)(this["ShortTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lists")]
        public string DefaultPropertiesFolder {
            get {
                return ((string)(this["DefaultPropertiesFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assemblies")]
        public string DefaultAssembliesFolder {
            get {
                return ((string)(this["DefaultAssembliesFolder"]));
            }
            set {
                this["DefaultAssembliesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
            set {
                this["Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sizes.xml")]
        public string SizesFilename {
            get {
                return ((string)(this["SizesFilename"]));
            }
            set {
                this["SizesFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pitches.xml")]
        public string PitchesFilename {
            get {
                return ((string)(this["PitchesFilename"]));
            }
            set {
                this["PitchesFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bom-{0}.xml")]
        public string BomFilenameFormat {
            get {
                return ((string)(this["BomFilenameFormat"]));
            }
            set {
                this["BomFilenameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float DefaultPitch {
            get {
                return ((float)(this["DefaultPitch"]));
            }
            set {
                this["DefaultPitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int PropertyRefreshInterval {
            get {
                return ((int)(this["PropertyRefreshInterval"]));
            }
            set {
                this["PropertyRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#585A77")]
        public string ItemSelectedBackgroundColor {
            get {
                return ((string)(this["ItemSelectedBackgroundColor"]));
            }
            set {
                this["ItemSelectedBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#606C72")]
        public string ItemHoverBackgroundColor {
            get {
                return ((string)(this["ItemHoverBackgroundColor"]));
            }
            set {
                this["ItemHoverBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4c565b")]
        public string ItemDefaultBackgroundColor {
            get {
                return ((string)(this["ItemDefaultBackgroundColor"]));
            }
            set {
                this["ItemDefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#06FFFFFF")]
        public string ItemAltnernateBackgroundColor {
            get {
                return ((string)(this["ItemAltnernateBackgroundColor"]));
            }
            set {
                this["ItemAltnernateBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int BomListFontSize {
            get {
                return ((int)(this["BomListFontSize"]));
            }
            set {
                this["BomListFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("debug.log")]
        public string DebugFilename {
            get {
                return ((string)(this["DebugFilename"]));
            }
            set {
                this["DebugFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Length")]
        public string Inventory_DefaultSearchBy {
            get {
                return ((string)(this["Inventory_DefaultSearchBy"]));
            }
            set {
                this["Inventory_DefaultSearchBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmClose {
            get {
                return ((bool)(this["ConfirmClose"]));
            }
            set {
                this["ConfirmClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#494d4f")]
        public string WindowBackgroundColor {
            get {
                return ((string)(this["WindowBackgroundColor"]));
            }
            set {
                this["WindowBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dddddd")]
        public string MenuBarBackgroundColor {
            get {
                return ((string)(this["MenuBarBackgroundColor"]));
            }
            set {
                this["MenuBarBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dddddd")]
        public string FieldButtonBackgroundColor {
            get {
                return ((string)(this["FieldButtonBackgroundColor"]));
            }
            set {
                this["FieldButtonBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dddddd")]
        public string LabelForegroundColor {
            get {
                return ((string)(this["LabelForegroundColor"]));
            }
            set {
                this["LabelForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#454545")]
        public string TextboxForegroundColor {
            get {
                return ((string)(this["TextboxForegroundColor"]));
            }
            set {
                this["TextboxForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4f626d")]
        public string TextboxBorderColor {
            get {
                return ((string)(this["TextboxBorderColor"]));
            }
            set {
                this["TextboxBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float DefaultSize {
            get {
                return ((float)(this["DefaultSize"]));
            }
            set {
                this["DefaultSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inventory.mdf")]
        public string DefaultInventoryPath {
            get {
                return ((string)(this["DefaultInventoryPath"]));
            }
            set {
                this["DefaultInventoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.###")]
        public string FloatFormatSpecifier {
            get {
                return ((string)(this["FloatFormatSpecifier"]));
            }
            set {
                this["FloatFormatSpecifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imperialSizes.xml")]
        public string ImperialSizesFilename {
            get {
                return ((string)(this["ImperialSizesFilename"]));
            }
            set {
                this["ImperialSizesFilename"] = value;
            }
        }
    }
}
