//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slate_EK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FASTener")]
        public string AppTitle {
            get {
                return ((string)(this["AppTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FASTener")]
        public string ShortTitle {
            get {
                return ((string)(this["ShortTitle"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fasteners")]
        public string DefaultFastenersFolder {
            get {
                return ((string)(this["DefaultFastenersFolder"]));
            }
            set {
                this["DefaultFastenersFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties")]
        public string DefaultPropertiesFolder {
            get {
                return ((string)(this["DefaultPropertiesFolder"]));
            }
            set {
                this["DefaultPropertiesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assemblies")]
        public string DefaultAssembliesFolder {
            get {
                return ((string)(this["DefaultAssembliesFolder"]));
            }
            set {
                this["DefaultAssembliesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
            set {
                this["Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sizes.xml")]
        public string SizesFilename {
            get {
                return ((string)(this["SizesFilename"]));
            }
            set {
                this["SizesFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pitches.xml")]
        public string PitchesFilename {
            get {
                return ((string)(this["PitchesFilename"]));
            }
            set {
                this["PitchesFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int SerializedUpdateInterval {
            get {
                return ((int)(this["SerializedUpdateInterval"]));
            }
            set {
                this["SerializedUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bom-{0}.xml")]
        public string BomFilenameFormat {
            get {
                return ((string)(this["BomFilenameFormat"]));
            }
            set {
                this["BomFilenameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double DefaultSize {
            get {
                return ((double)(this["DefaultSize"]));
            }
            set {
                this["DefaultSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double DefaultPitch {
            get {
                return ((double)(this["DefaultPitch"]));
            }
            set {
                this["DefaultPitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int PropertyRefreshInterval {
            get {
                return ((int)(this["PropertyRefreshInterval"]));
            }
            set {
                this["PropertyRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#585A77")]
        public string ItemSelectedBackgroundColor {
            get {
                return ((string)(this["ItemSelectedBackgroundColor"]));
            }
            set {
                this["ItemSelectedBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#606C72")]
        public string ItemHoverBackgroundColor {
            get {
                return ((string)(this["ItemHoverBackgroundColor"]));
            }
            set {
                this["ItemHoverBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4c565b")]
        public string ItemDefaultBackgroundColor {
            get {
                return ((string)(this["ItemDefaultBackgroundColor"]));
            }
            set {
                this["ItemDefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#50595E")]
        public string ItemAltnernateBackgroundColor {
            get {
                return ((string)(this["ItemAltnernateBackgroundColor"]));
            }
            set {
                this["ItemAltnernateBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties\\\\default_fastener.xml")]
        public string DefaultFastenerFilePath {
            get {
                return ((string)(this["DefaultFastenerFilePath"]));
            }
            set {
                this["DefaultFastenerFilePath"] = value;
            }
        }
    }
}
